FROM node:20-alpine

WORKDIR /app

# Copy dependency files first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy backend source
COPY . .

EXPOSE 3000

CMD ["npm", "run","start"]
